import Section from "./Section";
import ProjectCard from "./ProjectCard";

const ProjectsSection = () => {
  const projects = [
    {
      title: "WingZone",
      subtitle: "Food Delivery & Restaurant Management Platform",
      tech: "Next.js, Node.js, Express, MongoDB, Redis, Razorpay, Cloudflare R2, Docker",
      bullets: [
        "Architected a multi-tenant platform with 3 role-based portals, 24 feature modules, and 120+ REST endpoints serving customers, restaurants, and admins.",
        "Secured the platform with JWT access/refresh tokens and 3-role RBAC. Cut average API response time by ~70% using a Redis caching layer with MongoDB fallback.",
        "Integrated Razorpay payments with HMAC-verified webhooks. Containerized the app with Docker and reduced media load time by ~80% via Cloudflare R2 CDN.",
      ],
    },
    {
      title: "CraftQuote",
      subtitle: "Multi-Tenant SaaS Invoice Generation Platform",
      tech: "React 19, Vite, Tailwind CSS, Node.js, Express 5, MongoDB, Puppeteer, JWT",
      bullets: [
        "Built a multi-tenant SaaS invoicing platform with 30+ REST endpoints. Isolated tenants on a single database through 3-layer middleware.",
        "Designed a quote builder with 9 server-rendered PDF invoice templates generated by Puppeteer.",
        "Enforced 3-tier RBAC and a 2-tier subscription system. Hardened APIs with Helmet, rate limiting, XSS/NoSQL sanitization, and Winston logging.",
      ],
    },
    {
      title: "JEE Mains Portal",
      subtitle: "Multi-Tenant Online Examination Platform",
      tech: "React 19, Vite, Zustand, Node.js, Express 5, MongoDB, Redis, GitHub Actions, Cloudflare R2",
      bullets: [
        "Engineered a multi-tenant exam platform with college-based tenant isolation and 3-tier RBAC across 15+ REST domains.",
        "Developed an NTA-style exam engine for SCQ, MSQ, and FIB formats with negative marking and tamper prevention. Load-tested for 15,000+ concurrent test-takers.",
        "Automated bulk Excel imports of 1,000+ student records per upload. Lowered API latency by ~75% with Redis TTL caching and deployed via GitHub Actions CI/CD.",
      ],
    },
  ];

  return (
    <Section title="Projects">
      {projects.map((project, index) => (
        <ProjectCard key={index} {...project} />
      ))}
    </Section>
  );
};

export default ProjectsSection;
